name: CI

on: push

jobs:
  run-tests:
    name: Run test suite
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ["8.1", "8.2.5", "8.3.13", "8.4.1"]
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
      - run: composer install
      - run: php vendor/bin/php-cs-fixer check -v
      - run: php vendor/bin/phpunit
